# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthpalace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dad_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mom_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, choices=[('None', None), ('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], default='None', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=20, null=True),
        ),
    ]
