# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youthpalace', '0002_auto_20171231_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 2, 16, 47, 89860, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 2, 16, 47, 89795, tzinfo=utc)),
        ),
    ]
