# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youthpalace', '0003_auto_20171231_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 2, 17, 30, 164974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
