# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youthpalace', '0004_auto_20171231_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 31, 2, 19, 9, 880346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
