# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youthpalace', '0005_auto_20171231_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 31, 3, 39, 33, 92729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('女生', 'Female'), ('男生', 'Male')], max_length=20, null=True),
        ),
    ]
