# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 03:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youthpalace', '0006_auto_20171231_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_time',
            new_name='course_length',
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 31, 3, 41, 24, 572108, tzinfo=utc)),
        ),
    ]
